name: "Query upstream builds"
description: ""
inputs:
  upstream-builds:
    description: ""
    required: true
  query:
    description: ""
    required: true
  fail-on-empty:
    description: "Fail the action if any of queries results is empty"
    required: false
    default: "true"

outputs:
  result:
    description: ""

runs:
  using: node20
  main: "./dist/index.js"

branding:
  icon: "search"
  color: "blue"
