name: "build"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dist:
    name: Verify committed dist directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Calculate hash of committed `dist` directory
        run: echo "COMMITTED_HASH=${{ hashFiles('./dist/**') }}" >> $GITHUB_ENV

      - run: git config --global url."https://${{ secrets.CI_GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

      - run: yarn install

      - name: Calculate expected hash of `dist` directory
        run: |
          rm -rf dist && npm run prepare
          echo "EXPECTED_HASH=${{ hashFiles('./dist/**') }}" >> $GITHUB_ENV

      - name: Compare committed and expected hashes
        run: |
          echo "COMMITTED_HASH: ${{ env.COMMITTED_HASH }}"
          echo "EXPECTED_HASH: ${{ env.EXPECTED_HASH }}"

          export RESULT=$(expr "${{ env.COMMITTED_HASH }}" != "${{ env.EXPECTED_HASH }}")
          echo "RESULT: $RESULT"
          exit $RESULT

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
     
      - run: git config --global url."https://${{ secrets.CI_GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

      - run: yarn install

      - run: yarn run lint
