name: "NPM Package Version Bump"
description: "Bumps version of NPM package"
inputs:
  work-dir:
    description: "Directory containing `package.json` file"
    required: false
    default: "."
  is-prerelease:
    description: "Should bump version for prerelease"
    required: false
    default: "true"
  environment:
    description: "Environment"
    required: false
    default: "pre"
  branch:
    description: "branch"
    required: false
  commit:
    description: "commit"
    required: false

outputs:
  version:
    description: "Resolved new version"

runs:
  using: "node12"
  main: "./dist/index.js"

branding:
  icon: 'arrow-up-circle'  
  color: 'blue'
