name: "Load Environment Variables Action"

on:
  pull_request:
    paths:
      - "config/env/**"
      - "actions/load-env-variables/**"
      - ".github/workflows/load-env-variables.yml"
  push:
    branches:
      - main
    paths:
      - "config/env/**"
      - "actions/load-env-variables/**"
      - ".github/workflows/load-env-variables.yml"
  workflow_dispatch:

jobs:
  load-env-variables-manual-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load environment variables
        uses: ./actions/load-env-variables
        with:
          environment: 'sepolia'
          ref: 'main'

      - name: Use imported variables
        run: |
          echo "NETWORK_ID =  ${{ env.NETWORK_ID }}"
