name: Main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the build for'
        required: false
        default: 'ropsten'
      upstream_builds:
        description: 'Upstream builds, if empty runs a default workflow'
        required: false
      upstream_ref:
        description: 'Ref'
        required: false
        default: 'master'

jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Invoke downstream workflows
        uses: keep-network/run-workflow@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          environment: ${{ github.event.inputs.environment }}
          upstream_builds: ${{ github.event.inputs.upstream_builds }}
          upstream_ref: ${{ github.event.inputs.upstream_ref }}
