name: Main

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the build for'
        required: false
        default: 'dev'
      upstream_builds:
        description: 'Upstream builds, if empty runs a default workflow'
        required: false
      ref:
        description: 'Ref'
        required: false
        default: 'master'

jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
      - name: Show workflow dispatch parameters
        run: |
          echo "Workflow dispatched on branch: ${{ github.ref }}"
          echo "environment = ${{ github.event.inputs.environment }}"
          echo "upstream_builds = ${{ github.event.inputs.upstream_builds }}"
          echo "ref = ${{ github.event.inputs.ref }}"

      - uses: actions/checkout@v2

      - name: Invoke downstream workflow
        uses: keep-network/run-workflow@rfc-18/integration # TODO: replace 'rfc-18/integration ' with 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          environment: ${{ github.event.inputs.environment }}
          upstream_builds: ${{ github.event.inputs.upstream_builds }}
          ref: 'rfc-18/integration' # TODO: change later to ${{ github.event.inputs.ref }}
