name: "Test npm-version-bump"
on:
  pull_request:
    paths:
      - "actions/npm-version-bump/**"
      - ".github/workflows/test-npm-version-bump.yml"
  push:
    branches:
      - v1
    paths:
      - "actions/npm-version-bump/**"
      - ".github/workflows/test-npm-version-bump.yml"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./actions/npm-version-bump

jobs:
  npm-version-bump-dist:
    name: Verify committed dist directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Calculate hash of committed `dist` directory
        run: echo "COMMITTED_HASH=${{ hashFiles('./dist/**') }}" >> $GITHUB_ENV

      - run: yarn install

      - name: Calculate expected hash of `dist` directory
        run: |
          rm -rf dist && yarn run prepare
          echo "EXPECTED_HASH=${{ hashFiles('./dist/**') }}" >> $GITHUB_ENV

      - name: Compare committed and expected hashes
        run: |
          echo "COMMITTED_HASH: ${{ env.COMMITTED_HASH }}"
          echo "EXPECTED_HASH: ${{ env.EXPECTED_HASH }}"

          export RESULT=$(expr "${{ env.COMMITTED_HASH }}" != "${{ env.EXPECTED_HASH }}")
          echo "RESULT: $RESULT"
          exit $RESULT

  npm-version-bump-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run lint

  # unit tests
  npm-version-bump-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run test

  # test action works running from the graph
  npm-version-bump-manual-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ./tmp && cp ./test/data/package.json ./tmp
      - uses: keep-network/ci/actions/npm-version-bump@move-actions-to-ci #TODO: chage to @v1
        id: bump-version
        with:
          work-dir: ./actions/npm-version-bump/tmp
          environment: "ropsten"
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}
      # Print results of action execution to verify them.
      - name: Print package.json content
        run: cat ./tmp/package.json
      - name: Print resolved version
        run: echo "Resolved new version ${{ steps.bump-version.outputs.version }}"
