name: Test

on: [push, workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Load environment variables
        uses: keep-network/load-env-variables@v1
        with:
          environment: 'ropsten'
          ref: 'master'

      - name: Use imported variables
        run: |
          echo "NETWORK_ID =  ${{ env.NETWORK_ID }}"